# Alembic configuration file

[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/scrum_db
sqlalchemy.echo = False
sqlalchemy.echo_pool = False
sqlalchemy.pool_pre_ping = true
sqlalchemy.pool_recycle = 3600

sqlmodel.url = 

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
